# アクセス流量制限の定義
limit_req_zone $binary_remote_addr zone=one:10m rate=30r/s;

# djangoグループ作成
upstream django {
    server web:8000;
}

server {
    listen       80;
    listen  [::]:80;
    server_name  HackathonB-TeamLB-1856802156.ap-northeast-1.elb.amazonaws.com;
    # バージョン番号をエラーページとヘッダーに含まない
    server_tokens off;
    # サイトが読み込んでいいリソースを制限
    add_header Content-Security-Policy "
    default-src 'self';
    script-src 'self' 'unsafe-inline';
    style-src 'self' 'unsafe-inline';
    img-src 'self' data:;
    font-src 'self' data:;
    " always;

    #access_log  /var/log/nginx/host.access.log  main;

    location / {
        # リクエストをdjangoグループへ渡す
        proxy_pass http://django;
        # 元のホストヘッダーを80番ポートのWebサーバーに転送
        proxy_set_header Host $host;
        # クライアントの実際のIPを80番ポートのWebサーバーに転送
        proxy_set_header X-Real-IP $remote_addr;
        # プロキシ経由IPの履歴をX-Forwarded-Forヘッダーに追加
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        # クライアントが使ったプロトコル（HTTPまたはHTTPS）を80番ポートのWebサーバーに転送
        proxy_set_header X-Forwarded-Proto $scheme;
        # 技術情報をヘッダーに含めない(例:X-Powered-By: Djangoをヘッダーに含めない)
        proxy_hide_header X-Powered-By;
        # アクセス制限を適用&瞬間的なアクセス増加を許容
        limit_req zone=one burst=20;

        # タイムアウト設定
        proxy_connect_timeout 300;
        proxy_send_timeout 300;
        proxy_read_timeout 300;
    }

    # ALBヘルスチェック
    location = /health/ {
    access_log off;
    return 200 "OK";
    }

    # 静的ファイル配信設定
    location /static/ {
    root /code/staticfiles/;
    }

    error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        # 本番、/code/staticfiles/へ変更
        root   /usr/share/nginx/html;
    }

}

