# djangoグループ作成
upstream django {
    server web:8000;
}

server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;
    # バージョン番号をエラーページとヘッダーに含まない
    server_tokens off;
    # クリックジャンキング対策
    add_header X-Frame-Options SAMEORIGIN;
    # サイトが読み込んでいいリソースを制限
    add_header Content-Security-Policy "default-src 'self'" 'unsafe-inline';
    # MIMEスニッフィング対策
    add_header X-Content-Type-Options nosniff;

    #access_log  /var/log/nginx/host.access.log  main;

    location / {
        # リクエストをdjangoグループへ渡す
        proxy_pass http://django;
        # 元のホストヘッダーを80番ポートのWebサーバーに転送
        proxy_set_header Host $host;
        # クライアントの実際のIPを80番ポートのWebサーバーに転送
        proxy_set_header X-Real-IP $remote_addr;
        # プロキシ経由IPの履歴をX-Forwarded-Forヘッダーに追加
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        # クライアントが使ったプロトコル（HTTPまたはHTTPS）を80番ポートのWebサーバーに転送
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

}

