services:          
  web:
    build: 
      # ビルドコンテナはカレントディレクトリ
      context: .
      dockerfile: dockerfiles/django/Dockerfile
    # 静的ファイル収集、gunicorn起動 gunicornの設定を適応
    command: >
      sh -c "
      python manage.py collectstatic --noinput &&
      gunicorn djangopj.wsgi:application --config /code/dockerfiles/django/gunicorn_config.py"
    environment:
      TZ: Asia/Tokyo
    env_file:
      - .env
    # 静的ファイルをwebとnginxコンテナで共有
    volumes:
      - static_volume:/code/staticfiles
    # コンテナ内でポート番号8000使用を宣言
    expose:
      - "8000"
    # 手動停止以外で停止した場合コンテナ再起動
    restart: unless-stopped
    # ロギングドライバ
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-northeast-1
        awslogs-group: HackathonB-Team
        tag: "{{.Name}}.{{.FullID}}"

  nginx:
    build:
      context: .
      dockerfile: dockerfiles/nginx/Dockerfile
    image: b-team_nginx
    environment:
      TZ: Asia/Tokyo
    ports:
      - 80:80
    # 静的ファイルをwebとnginxコンテナで共有
    volumes:
      - static_volume:/code/staticfiles
    depends_on:
      - web
    # 手動停止以外で停止した場合コンテナ再起動
    restart: unless-stopped
    # ロギングドライバ
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-northeast-1
        awslogs-group: HackathonB-Team
        tag: "{{.Name}}.{{.FullID}}"

# コンテナ間で静的ファイルを共有する
volumes:
  static_volume: