services:          
  db:
    image: mysql:8.3   
    environment:             
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: django-db
      MYSQL_USER: django
      MYSQL_PASSWORD: django
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - "3306:3306"

  web:
    build: 
      # ビルドコンテナはカレントディレクトリ
      context: .
      dockerfile: dockerfiles/django/Dockerfile
    command: gunicorn djangopj.wsgi:application --config /code/dockerfiles/django/gunicorn_config.py
    volumes:               
      - .:/code
    ports:                  
      - "8000:8000"
    depends_on:             
      - db

  nginx:
    build:
      context: .
      dockerfile: dockerfiles/nginx/Dockerfile
    image: b-team_nginx
    ports:
      - 80:80