services:          
  web:
    build: 
      # ビルドコンテナはカレントディレクトリ
      context: .
      dockerfile: dockerfiles/django/Dockerfile
    # gunicorn起動 gunicornの設定を適応
    command: gunicorn djangopj.wsgi:application --config /code/dockerfiles/django/gunicorn_config.py
    environment:
      TZ: Asia/Tokyo
    volumes:               
      - .:/code
    # コンテナ内でポート番号8000使用を宣言
    expose:
      - "8000"
    depends_on:             
      - db
    # 手動停止以外で停止した場合コンテナ再起動
    restart: unless-stopped
    # ロギングドライバ
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-northeast-1
        awslogs-group: HackathonB-Team
        tag: "{{.imageName}}.{{.Name}}.{{.FullID}}"

  nginx:
    build:
      context: .
      dockerfile: dockerfiles/nginx/Dockerfile
    image: b-team_nginx
    environment:
      TZ: Asia/Tokyo
    ports:
      - 80:80
    depends_on:
      - web
    # 手動停止以外で停止した場合コンテナ再起動
    restart: unless-stopped
    # ロギングドライバ
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-northeast-1
        awslogs-group: HackathonB-Team
        tag: "{{.imageName}}.{{.Name}}.{{.FullID}}"