# Generated by Django 5.0 on 2026-05-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_make_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='link_name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
