# Generated by Django 5.0 on 2026-05-28 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_link_name_to_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetail',
            name='memo',
            field=models.TextField(null=True),
        ),
    ]
